#!/usr/bin/env node
/**
 * Claude for Word RTL Fix - CSS + typography injector.
 *
 * Connects to WebView2's Chrome DevTools Protocol on localhost:9222,
 * finds the Claude panel, and injects:
 *   - RTL CSS (direction, list markers, tables, code)
 *   - MutationObserver that replaces em-dash/en-dash with hyphen,
 *     and arrows (U+2190-U+2199, U+21D0-U+21D4) with commas in visible text.
 *
 * All processing is local. No network traffic is generated by this script.
 * Runs until Ctrl+C. Re-injects automatically when the panel reloads.
 */

const CDP = require('chrome-remote-interface');
const http = require('http');
const fs = require('fs');
const path = require('path');
const portDiscovery = require('./port-discovery');
const officeApps = require('../lib/office-apps');

const TEMP_DIR = process.env.TEMP || process.env.TMP || '.';
// Aggregate status file polled by the tray icon PowerShell script for icon
// color. One-line ASCII. Values: CONNECTED | DISCONNECTED | ERROR:<message>.
// "Aggregate" because it reflects the overall injector state, not per-app.
// The per-app states are written to APPS_STATUS_FILE below for the tray's
// per-app status labels.
const STATUS_FILE = path.join(TEMP_DIR, 'claude-word-rtl.status');
// Per-app status file (v0.2.0+). One JSON object keyed by app name with
// values CONNECTED | DISCONNECTED. The tray reads this each tick to render
// per-app labels (Word: connected, Excel: not running, etc). Aggregate
// status (above) is still the icon-color source of truth.
const APPS_STATUS_FILE = path.join(TEMP_DIR, 'claude-office-rtl.apps.json');
// PID file so cleanup scripts can target THIS injector specifically
// instead of killing every node.exe on the machine.
const PID_FILE = path.join(TEMP_DIR, 'claude-word-rtl.pid');
// Rolling diagnostic log, truncated on each injector start so we only
// keep the current session's activity. Used to diagnose Connect failures.
// NOTE: truncate happens AFTER acquireSingletonLock() below, so duplicate
// launches that exit silently do not clobber the running injector's log.
const LOG_FILE = path.join(TEMP_DIR, 'claude-word-rtl.log');
// Per-app opt-in flag files for apps in officeApps.BLOCKED_HOST_INFO_KEYS.
// Existence of the file = user has explicitly opted this app in for the
// current injector session. Written by the matching wrapper (e.g. the future
// outlook-wrapper.bat). Stale-cleared at injector startup so a previous
// session's consent never carries silently into a new session.
const OPTIN_FLAGS = {
  outlook: path.join(TEMP_DIR, 'claude-office-rtl.outlook-optin'),
};
function fileLog(msg) {
  try {
    fs.appendFileSync(LOG_FILE, new Date().toISOString() + ' ' + msg + '\n');
  } catch (e) { /* best-effort */ }
}

// Track whether we've entered ERROR state so the next successful inject
// doesn't silently overwrite it back to CONNECTED on the same tick.
var inErrorState = false;
function writeStatus(s) {
  if (inErrorState && s === 'CONNECTED') return;
  if (s && s.indexOf('ERROR:') === 0) inErrorState = true;
  if (s === 'DISCONNECTED') inErrorState = false;
  try { fs.writeFileSync(STATUS_FILE, s + '\n'); } catch (e) { /* best-effort */ }
}
function isPidAlive(pid) {
  if (!pid || isNaN(pid)) return false;
  try {
    // Signal 0 is a no-op probe: throws if the process is gone, returns
    // silently if it exists. EPERM means it exists but we cannot signal it
    // (still proves existence).
    process.kill(pid, 0);
    return true;
  } catch (e) {
    return e.code === 'EPERM';
  }
}
// Singleton enforcement. Three independent paths can spawn this script
// (the three Office wrappers, the tray auto-launch, and any manual
// inject-hidden.vbs invocation), and they do NOT all coordinate on the
// lock file. Race + non-coordinated paths historically left two or three
// node processes running concurrently, each racing to inject the same
// CSS into the same CDP target and clobbering each other's status writes.
// Use the PID file itself as a real mutex via O_EXCL ('wx'): the first
// caller to atomically create the file wins; duplicates exit silently.
// Stale files (whose recorded PID is dead) are removed so a crash does
// not lock out the next legitimate launch.
function acquireSingletonLock() {
  for (var attempt = 0; attempt < 2; attempt++) {
    try {
      var fd = fs.openSync(PID_FILE, 'wx');
      fs.writeSync(fd, String(process.pid) + '\n');
      fs.closeSync(fd);
      return;
    } catch (e) {
      if (e.code !== 'EEXIST') throw e;
      var owner = null;
      try { owner = parseInt(fs.readFileSync(PID_FILE, 'utf8').trim(), 10); } catch (_) {}
      if (owner && owner !== process.pid && isPidAlive(owner)) {
        // Another live injector owns the lock. Exit silently and let it
        // handle injection. Do not touch LOG_FILE - we haven't truncated
        // yet, so the running instance's log is preserved.
        process.exit(0);
      }
      // Stale lock from a dead PID. Remove and retry exactly once.
      try { fs.unlinkSync(PID_FILE); } catch (_) {}
    }
  }
  // Two attempts both lost the race to another concurrent starter.
  // Defer to the winner.
  process.exit(0);
}
function removePidFile() {
  // Only remove if the PID file still records us as the owner. Guards
  // against a SIGTERM-during-startup race where a newer injector has
  // already acquired the lock and we would otherwise wipe its PID.
  try {
    var current = parseInt(fs.readFileSync(PID_FILE, 'utf8').trim(), 10);
    if (current === process.pid) fs.unlinkSync(PID_FILE);
  } catch (e) { /* best-effort */ }
}
// Per-app status writer. Builds {Word: ..., Excel: ..., PowerPoint: ...}
// from the current attach map. Called from tick() after target reconcile,
// and during shutdown to leave a clean DISCONNECTED record on disk.
function writeAppsStatus(connectedAppNames) {
  var state = {};
  for (var i = 0; i < officeApps.APPS.length; i++) {
    var name = officeApps.APPS[i].name;
    state[name] = connectedAppNames.has(name) ? 'CONNECTED' : 'DISCONNECTED';
  }
  // Atomic write: write to a temp sibling and rename. Avoids the tray
  // (PowerShell, polling every 2s) reading a half-written JSON object.
  try {
    var tmp = APPS_STATUS_FILE + '.tmp';
    fs.writeFileSync(tmp, JSON.stringify(state) + '\n');
    fs.renameSync(tmp, APPS_STATUS_FILE);
  } catch (e) { /* best-effort */ }
}
function writeAppsAllDisconnected() {
  writeAppsStatus(new Set());
}
acquireSingletonLock();
// Truncate the rolling log only AFTER we won the singleton lock. A
// duplicate launch that exits via acquireSingletonLock() must not clobber
// the running injector's log file.
try { fs.writeFileSync(LOG_FILE, ''); } catch (e) { /* best-effort */ }
// Clear any leftover opt-in flags. A new injector session always starts
// with all blocked apps blocked; the matching wrapper must re-create the
// flag on each launch.
Object.keys(OPTIN_FLAGS).forEach(function (k) {
  try { fs.unlinkSync(OPTIN_FLAGS[k]); } catch (e) { /* missing is fine */ }
});
writeStatus('DISCONNECTED');
writeAppsAllDisconnected();
process.on('exit', function () {
  writeStatus('DISCONNECTED');
  writeAppsAllDisconnected();
  removePidFile();
});
process.on('SIGINT', function () {
  writeStatus('DISCONNECTED');
  writeAppsAllDisconnected();
  removePidFile();
  process.exit(0);
});
process.on('SIGTERM', function () {
  writeStatus('DISCONNECTED');
  writeAppsAllDisconnected();
  removePidFile();
  process.exit(0);
});

// One-shot flag: emit the "DOM doesn't match" warning at most once per
// process lifetime so re-injects on every 2s tick don't spam the terminal.
var domWarningEmitted = false;
// Prefer the WebView2 panel URL (pivot.claude.ai), fall back to any claude.ai
// host for forward/backward compatibility if Anthropic changes the subdomain.
// Patterns anchor on "//" + optional subdomain + host + "/" so that we match
// the hostname component specifically, not a substring anywhere in the URL.
// Fallback intentionally excludes anthropic.com to avoid matching unrelated
// pages (console, docs, blog) that might load in WebView2.
const URL_PATTERN_PRIMARY = /\/\/([^\/]*\.)?pivot\.claude\.ai(\/|$|\?|#)/i;
const URL_PATTERN_FALLBACK = /\/\/([^\/]*\.)?claude\.ai(\/|$|\?|#)/i;
const POLL_MS = 2000;

const RTL_CSS = `
  /* Claude-RTL-Fix: base RTL + fixed list markers + code handling.
     Font family is intentionally NOT set, so Claude's own UI font is preserved. */
  html, body { direction: rtl !important; }
  p, li, td, th, h1, h2, h3, h4, h5, h6, blockquote, figcaption { text-align: start; }
  p, div, span, li, td, th, h1, h2, h3, h4, h5, h6, blockquote, figcaption {
    direction: rtl !important;
    unicode-bidi: isolate !important;
  }
  /* list containers must be RTL so markers (1. 2. •) render on the right */
  ol, ul, dl, menu {
    direction: rtl !important;
    unicode-bidi: isolate !important;
  }
  /* input fields */
  textarea, input[type="text"], input[type="search"], [contenteditable="true"] {
    direction: rtl !important;
    text-align: start !important;
    unicode-bidi: isolate !important;
  }
  /* code blocks stay LTR for code correctness */
  pre, pre *, code, kbd, samp, tt, .hljs, [class*="language-"], [class*="code-"] {
    direction: ltr !important;
    text-align: left !important;
    unicode-bidi: isolate !important;
  }
  /* inline code inside Hebrew paragraphs - isolate so Hebrew flow stays RTL */
  p code, li code, td code, th code, span code, div > code {
    unicode-bidi: isolate !important;
  }
  /* tables */
  table { direction: rtl !important; }
`;

const INJECTOR_SCRIPT = `
(function () {
  var id = '__claude_rtl_fix__';
  var old = document.getElementById(id);
  if (old) old.remove();
  var style = document.createElement('style');
  style.id = id;
  style.textContent = ${JSON.stringify(RTL_CSS)};
  (document.head || document.documentElement).appendChild(style);

  // Hebrew typography fix: em-dash/en-dash -> hyphen, arrows -> comma.
  // Runs on text nodes. Never touches input fields (preserves user typing).
  // Mutations are batched via requestAnimationFrame to keep long streaming
  // sessions cheap.
  if (!window.__claude_typo_observer__) {
    var REPLACERS = [
      { from: /[\\u2014\\u2013]/g, to: '-' },
      { from: /[\\u2190-\\u2199\\u21D0-\\u21D4]/g, to: ',' },
      { from: /&rarr;|&larr;|&uarr;|&darr;/g, to: ',' }
    ];
    function isInCodeBlock(node) {
      // Walk up to find any PRE or CODE ancestor. Text inside code blocks
      // must never be modified - em-dashes and arrows can be semantically
      // meaningful in source code.
      var el = node.nodeType === 1 ? node : node.parentElement;
      while (el) {
        var tn = el.tagName;
        if (tn === 'PRE' || tn === 'CODE' || tn === 'KBD' || tn === 'SAMP') return true;
        el = el.parentElement;
      }
      return false;
    }
    function fixNode(node) {
      if (node.nodeType === 3) {
        if (isInCodeBlock(node)) return;
        var t = node.nodeValue;
        var changed = false;
        for (var i = 0; i < REPLACERS.length; i++) {
          var before = t;
          t = t.replace(REPLACERS[i].from, REPLACERS[i].to);
          if (t !== before) changed = true;
        }
        if (changed) node.nodeValue = t;
      } else if (node.nodeType === 1) {
        var tag = node.tagName;
        if (tag === 'TEXTAREA' || tag === 'INPUT' || node.isContentEditable) return;
        if (tag === 'PRE' || tag === 'CODE' || tag === 'KBD' || tag === 'SAMP') return;
        for (var c = node.firstChild; c; c = c.nextSibling) fixNode(c);
      }
    }
    fixNode(document.body);

    var pending = new Set();
    var scheduled = false;
    function flush() {
      scheduled = false;
      var nodes = pending;
      pending = new Set();
      nodes.forEach(fixNode);
    }
    function schedule(node) {
      pending.add(node);
      if (!scheduled) {
        scheduled = true;
        requestAnimationFrame(flush);
      }
    }

    var obs = new MutationObserver(function (muts) {
      for (var i = 0; i < muts.length; i++) {
        var m = muts[i];
        if (m.type === 'characterData') schedule(m.target);
        else if (m.addedNodes) {
          for (var j = 0; j < m.addedNodes.length; j++) schedule(m.addedNodes[j]);
        }
      }
    });
    obs.observe(document.body, { childList: true, subtree: true, characterData: true });
    window.__claude_typo_observer__ = obs;
  }

  return old ? 'replaced' : 'injected';
})();
`;

const attached = new Map();

function log() {
  var ts = new Date().toISOString().slice(11, 19);
  var args = Array.prototype.slice.call(arguments);
  console.log.apply(console, ['[' + ts + ']'].concat(args));
  try { fileLog(args.map(function (a) { return typeof a === 'string' ? a : JSON.stringify(a); }).join(' ')); } catch (e) {}
}

// Runs inside the page context. Returns an object describing which of our
// expected invariants hold after the CSS has been injected. The injector
// sets <html dir style> via the RTL_CSS rule on `html, body`, so we check
// the computed direction rather than a literal inline-style equality (CSS
// !important doesn't show up on element.style).
const VALIDATION_SCRIPT = `
  (function () {
    try {
      var htmlDir = getComputedStyle(document.documentElement).direction;
      var bodyDir = document.body ? getComputedStyle(document.body).direction : '';
      var styleInjected = !!document.getElementById('__claude_rtl_fix__');
      // Representative selector: the Claude chat panel is built from <p>, <div>,
      // <textarea>. If none of these exist on a page we think is Claude, the
      // DOM has been radically restructured.
      var hasContent = document.querySelectorAll('p, textarea, [contenteditable="true"]').length > 0;
      return { htmlDir: htmlDir, bodyDir: bodyDir, styleInjected: styleInjected, hasContent: hasContent };
    } catch (e) {
      return { error: String(e) };
    }
  })();
`;

async function validateInjection(Runtime, url) {
  try {
    var r = await Runtime.evaluate({ expression: VALIDATION_SCRIPT, returnByValue: true });
    var v = r && r.result && r.result.value;
    if (!v) return;
    var ok = v.styleInjected && v.htmlDir === 'rtl' && v.hasContent;
    if (!ok && !domWarningEmitted) {
      domWarningEmitted = true;
      process.stderr.write('[WARN] Claude add-in DOM may have changed; selectors did not match. Check for an updated release of claude-word-rtl.\n');
      log('Validation failed for ' + url + ': ' + JSON.stringify(v));
      writeStatus('ERROR:dom-not-matched-after-inject');
    } else if (ok && inErrorState) {
      // Recovery: we were stuck in ERROR, but this tick validates clean.
      // Clear the flag and report CONNECTED so the tray goes green again.
      inErrorState = false;
      writeStatus('CONNECTED');
    }
  } catch (e) { /* ignore - next tick will retry */ }
}

async function attach(target, app, port) {
  if (attached.has(target.id)) return;
  var appName = app ? app.name : 'unknown';
  try {
    var client = await CDP({ target: target.webSocketDebuggerUrl });
    var Page = client.Page, Runtime = client.Runtime;
    await Page.enable();
    await Runtime.enable();
    await Page.addScriptToEvaluateOnNewDocument({ source: INJECTOR_SCRIPT });
    var result = await Runtime.evaluate({ expression: INJECTOR_SCRIPT, returnByValue: true });
    log('Attached & injected: [' + appName + '] port=' + port + ' url=' + target.url + ' -> ' + (result.result && result.result.value));
    // Track the app name and register the client in the attach map BEFORE
    // refreshing per-app status. refreshAppsStatus() iterates attached.values()
    // to derive the {Word/Excel/PowerPoint -> CONNECTED} map; if the client
    // is not yet in the map at that moment, the just-attached app is missed
    // and apps.json keeps reporting it as DISCONNECTED until the next
    // attach/disconnect event - which never comes for a stable session.
    client.__appName = appName;
    attached.set(target.id, client);
    writeStatus('CONNECTED');
    refreshAppsStatus();

    // Delayed validation: give the page 5s to settle (SPA hydration, async
    // chunks) before we declare the DOM "doesn't match".
    setTimeout(function () { validateInjection(Runtime, target.url); }, 5000);

    Page.on('frameNavigated', async function () {
      try {
        await Runtime.evaluate({ expression: INJECTOR_SCRIPT });
        // Re-run validation after navigation too, but the dedupe flag means
        // it only logs once per process.
        setTimeout(function () { validateInjection(Runtime, target.url); }, 5000);
      } catch (e) {}
    });

    client.on('disconnect', function () {
      log('Detached: [' + appName + '] port=' + port + ' url=' + target.url);
      attached.delete(target.id);
      if (attached.size === 0) writeStatus('DISCONNECTED');
      refreshAppsStatus();
    });
  } catch (err) {
    log('Attach failed for [' + appName + '] port=' + port + ' url=' + target.url + ': ' + err.message);
    fileLog('attach error stack: ' + (err && err.stack ? err.stack : '(no stack)'));
  }
}

// Walk the attach map, collect the app names of currently-attached targets,
// and write the per-app status file. Called whenever the set of attached
// targets changes (after attach success, after disconnect, after tick
// reconciles dropped targets).
function refreshAppsStatus() {
  var connected = new Set();
  for (var client of attached.values()) {
    if (client && client.__appName && client.__appName !== 'unknown') {
      connected.add(client.__appName);
    }
  }
  writeAppsStatus(connected);
}

// Tick counter + last-logged signatures so we can log state transitions
// without spamming the file every 2s. We log: every discovery error, the
// first successful tick, and any change in the set of matched targets.
var tickCount = 0;
var lastTargetsSig = null;
var lastListErrorMsg = null;
// target.id of blocked targets we have already logged a skip-line for, so
// the log gets one line per appearance of a blocked target, not one per
// 2s tick while it stays around. Pruned when the target goes away.
var loggedBlockedIds = new Set();

function readOptInKeys() {
  var keys = new Set();
  Object.keys(OPTIN_FLAGS).forEach(function (k) {
    try { if (fs.existsSync(OPTIN_FLAGS[k])) keys.add(k); } catch (e) {}
  });
  return keys;
}
// v0.2.0: removed port-9222-squat detection - dynamic ports avoid the squat
// pathology entirely. Each Office app gets its own ephemeral port via
// --remote-debugging-port=0, so a non-Office CDP app on a fixed port no
// longer interferes with discovery.
async function tick() {
  tickCount++;
  var results;
  try {
    results = await portDiscovery.discoverActiveTargets();
    if (lastListErrorMsg) {
      fileLog('discoverActiveTargets recovered after error: ' + lastListErrorMsg);
      lastListErrorMsg = null;
    }
  } catch (e) {
    var msg = e && e.message ? e.message : String(e);
    if (msg !== lastListErrorMsg) {
      fileLog('discoverActiveTargets failed (tick ' + tickCount + '): ' + msg);
      lastListErrorMsg = msg;
    }
    return;
  }
  // Drop attached entries whose target id is no longer present in the
  // current discovery results (page closed, Office app exited, etc).
  var aliveIds = new Set(results.map(function (r) { return r.target.id; }));
  var droppedAny = false;
  for (var id of Array.from(attached.keys())) {
    if (!aliveIds.has(id)) {
      attached.delete(id);
      droppedAny = true;
    }
  }
  // Prune the blocked-log set the same way - if a blocked target closed,
  // a future re-appearance should re-log.
  for (var bid of Array.from(loggedBlockedIds)) {
    if (!aliveIds.has(bid)) loggedBlockedIds.delete(bid);
  }
  // If any target was reaped here (disconnect handler may not have fired
  // for app-exit cases where CDP closes abruptly), refresh the per-app
  // status so the tray sees the change within one tick.
  if (droppedAny) refreshAppsStatus();
  var sig = 'matched=' + results.length +
    ' entries=[' + results.map(function (r) {
      return (r.app ? r.app.name : 'unknown') + '@' + r.port + ' ' + r.target.url;
    }).join(' | ') + ']';
  if (sig !== lastTargetsSig) {
    fileLog('targets (tick ' + tickCount + '): ' + sig);
    lastTargetsSig = sig;
  }

  var optInKeys = readOptInKeys();
  for (var i = 0; i < results.length; i++) {
    var r = results[i];
    if (attached.has(r.target.id)) continue;
    if (officeApps.isHostInfoBlocked(r.target.url, optInKeys)) {
      if (!loggedBlockedIds.has(r.target.id)) {
        loggedBlockedIds.add(r.target.id);
        fileLog('Blocked target (no opt-in): ' + officeApps.getHostInfoKey(r.target.url) +
                '@' + r.port + ' url=' + r.target.url);
      }
      continue;
    }
    await attach(r.target, r.app, r.port);
  }
}

log('Claude RTL injector starting. Discovering active Office WebView2 ports.');
log('Match pattern (primary):', URL_PATTERN_PRIMARY);
log('Match pattern (fallback):', URL_PATTERN_FALLBACK);
log('Ctrl+C to stop.');
setInterval(tick, POLL_MS);
tick();
