#!/usr/bin/env node
/**
 * Claude for Word RTL Fix - CSS + typography injector.
 *
 * Connects to WebView2's Chrome DevTools Protocol on localhost:9222,
 * finds the Claude panel, and injects:
 *   - RTL CSS (direction, list markers, tables, code)
 *   - MutationObserver that replaces em-dash/en-dash with hyphen,
 *     and arrows (U+2190-U+2199, U+21D0-U+21D4) with commas in visible text.
 *
 * All processing is local. No network traffic is generated by this script.
 * Runs until Ctrl+C. Re-injects automatically when the panel reloads.
 */

const CDP = require('chrome-remote-interface');
const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = 9222;
const TEMP_DIR = process.env.TEMP || process.env.TMP || '.';
// Status file polled by the tray icon PowerShell script. One-line ASCII.
// Values: CONNECTED | DISCONNECTED | ERROR:<message>
const STATUS_FILE = path.join(TEMP_DIR, 'claude-word-rtl.status');
// PID file so cleanup scripts can target THIS injector specifically
// instead of killing every node.exe on the machine.
const PID_FILE = path.join(TEMP_DIR, 'claude-word-rtl.pid');
// Rolling diagnostic log, truncated on each injector start so we only
// keep the current session's activity. Used to diagnose Connect failures.
const LOG_FILE = path.join(TEMP_DIR, 'claude-word-rtl.log');
try { fs.writeFileSync(LOG_FILE, ''); } catch (e) { /* best-effort */ }
function fileLog(msg) {
  try {
    fs.appendFileSync(LOG_FILE, new Date().toISOString() + ' ' + msg + '\n');
  } catch (e) { /* best-effort */ }
}

// Track whether we've entered ERROR state so the next successful inject
// doesn't silently overwrite it back to CONNECTED on the same tick.
var inErrorState = false;
function writeStatus(s) {
  if (inErrorState && s === 'CONNECTED') return;
  if (s && s.indexOf('ERROR:') === 0) inErrorState = true;
  if (s === 'DISCONNECTED') inErrorState = false;
  try { fs.writeFileSync(STATUS_FILE, s + '\n'); } catch (e) { /* best-effort */ }
}
function writePidFile() {
  try { fs.writeFileSync(PID_FILE, String(process.pid) + '\n'); } catch (e) { /* best-effort */ }
}
function removePidFile() {
  try { fs.unlinkSync(PID_FILE); } catch (e) { /* best-effort */ }
}
writePidFile();
writeStatus('DISCONNECTED');
process.on('exit', function () { writeStatus('DISCONNECTED'); removePidFile(); });
process.on('SIGINT', function () { writeStatus('DISCONNECTED'); removePidFile(); process.exit(0); });
process.on('SIGTERM', function () { writeStatus('DISCONNECTED'); removePidFile(); process.exit(0); });

// One-shot flag: emit the "DOM doesn't match" warning at most once per
// process lifetime so re-injects on every 2s tick don't spam the terminal.
var domWarningEmitted = false;
// Prefer the WebView2 panel URL (pivot.claude.ai), fall back to any claude.ai
// host for forward/backward compatibility if Anthropic changes the subdomain.
// Patterns anchor on "//" + optional subdomain + host + "/" so that we match
// the hostname component specifically, not a substring anywhere in the URL.
// Fallback intentionally excludes anthropic.com to avoid matching unrelated
// pages (console, docs, blog) that might load in WebView2.
const URL_PATTERN_PRIMARY = /\/\/([^\/]*\.)?pivot\.claude\.ai(\/|$|\?|#)/i;
const URL_PATTERN_FALLBACK = /\/\/([^\/]*\.)?claude\.ai(\/|$|\?|#)/i;
const POLL_MS = 2000;

const RTL_CSS = `
  /* Claude-RTL-Fix: base RTL + fixed list markers + code handling.
     Font family is intentionally NOT set, so Claude's own UI font is preserved. */
  html, body { direction: rtl !important; }
  p, li, td, th, h1, h2, h3, h4, h5, h6, blockquote, figcaption { text-align: start; }
  p, div, span, li, td, th, h1, h2, h3, h4, h5, h6, blockquote, figcaption {
    direction: rtl !important;
    unicode-bidi: isolate !important;
  }
  /* list containers must be RTL so markers (1. 2. •) render on the right */
  ol, ul, dl, menu {
    direction: rtl !important;
    unicode-bidi: isolate !important;
  }
  /* input fields */
  textarea, input[type="text"], input[type="search"], [contenteditable="true"] {
    direction: rtl !important;
    text-align: start !important;
    unicode-bidi: isolate !important;
  }
  /* code blocks stay LTR for code correctness */
  pre, pre *, code, kbd, samp, tt, .hljs, [class*="language-"], [class*="code-"] {
    direction: ltr !important;
    text-align: left !important;
    unicode-bidi: isolate !important;
  }
  /* inline code inside Hebrew paragraphs - isolate so Hebrew flow stays RTL */
  p code, li code, td code, th code, span code, div > code {
    unicode-bidi: isolate !important;
  }
  /* tables */
  table { direction: rtl !important; }
`;

const INJECTOR_SCRIPT = `
(function () {
  var id = '__claude_rtl_fix__';
  var old = document.getElementById(id);
  if (old) old.remove();
  var style = document.createElement('style');
  style.id = id;
  style.textContent = ${JSON.stringify(RTL_CSS)};
  (document.head || document.documentElement).appendChild(style);

  // Hebrew typography fix: em-dash/en-dash -> hyphen, arrows -> comma.
  // Runs on text nodes. Never touches input fields (preserves user typing).
  // Mutations are batched via requestAnimationFrame to keep long streaming
  // sessions cheap.
  if (!window.__claude_typo_observer__) {
    var REPLACERS = [
      { from: /[\\u2014\\u2013]/g, to: '-' },
      { from: /[\\u2190-\\u2199\\u21D0-\\u21D4]/g, to: ',' },
      { from: /&rarr;|&larr;|&uarr;|&darr;/g, to: ',' }
    ];
    function isInCodeBlock(node) {
      // Walk up to find any PRE or CODE ancestor. Text inside code blocks
      // must never be modified - em-dashes and arrows can be semantically
      // meaningful in source code.
      var el = node.nodeType === 1 ? node : node.parentElement;
      while (el) {
        var tn = el.tagName;
        if (tn === 'PRE' || tn === 'CODE' || tn === 'KBD' || tn === 'SAMP') return true;
        el = el.parentElement;
      }
      return false;
    }
    function fixNode(node) {
      if (node.nodeType === 3) {
        if (isInCodeBlock(node)) return;
        var t = node.nodeValue;
        var changed = false;
        for (var i = 0; i < REPLACERS.length; i++) {
          var before = t;
          t = t.replace(REPLACERS[i].from, REPLACERS[i].to);
          if (t !== before) changed = true;
        }
        if (changed) node.nodeValue = t;
      } else if (node.nodeType === 1) {
        var tag = node.tagName;
        if (tag === 'TEXTAREA' || tag === 'INPUT' || node.isContentEditable) return;
        if (tag === 'PRE' || tag === 'CODE' || tag === 'KBD' || tag === 'SAMP') return;
        for (var c = node.firstChild; c; c = c.nextSibling) fixNode(c);
      }
    }
    fixNode(document.body);

    var pending = new Set();
    var scheduled = false;
    function flush() {
      scheduled = false;
      var nodes = pending;
      pending = new Set();
      nodes.forEach(fixNode);
    }
    function schedule(node) {
      pending.add(node);
      if (!scheduled) {
        scheduled = true;
        requestAnimationFrame(flush);
      }
    }

    var obs = new MutationObserver(function (muts) {
      for (var i = 0; i < muts.length; i++) {
        var m = muts[i];
        if (m.type === 'characterData') schedule(m.target);
        else if (m.addedNodes) {
          for (var j = 0; j < m.addedNodes.length; j++) schedule(m.addedNodes[j]);
        }
      }
    });
    obs.observe(document.body, { childList: true, subtree: true, characterData: true });
    window.__claude_typo_observer__ = obs;
  }

  return old ? 'replaced' : 'injected';
})();
`;

const attached = new Map();

function log() {
  var ts = new Date().toISOString().slice(11, 19);
  var args = Array.prototype.slice.call(arguments);
  console.log.apply(console, ['[' + ts + ']'].concat(args));
  try { fileLog(args.map(function (a) { return typeof a === 'string' ? a : JSON.stringify(a); }).join(' ')); } catch (e) {}
}

function listTargets() {
  return new Promise(function (resolve, reject) {
    http.get('http://localhost:' + PORT + '/json/list', function (res) {
      var body = '';
      res.on('data', function (c) { body += c; });
      res.on('end', function () {
        try { resolve(JSON.parse(body)); } catch (e) { reject(e); }
      });
    }).on('error', reject);
  });
}

// Runs inside the page context. Returns an object describing which of our
// expected invariants hold after the CSS has been injected. The injector
// sets <html dir style> via the RTL_CSS rule on `html, body`, so we check
// the computed direction rather than a literal inline-style equality (CSS
// !important doesn't show up on element.style).
const VALIDATION_SCRIPT = `
  (function () {
    try {
      var htmlDir = getComputedStyle(document.documentElement).direction;
      var bodyDir = document.body ? getComputedStyle(document.body).direction : '';
      var styleInjected = !!document.getElementById('__claude_rtl_fix__');
      // Representative selector: the Claude chat panel is built from <p>, <div>,
      // <textarea>. If none of these exist on a page we think is Claude, the
      // DOM has been radically restructured.
      var hasContent = document.querySelectorAll('p, textarea, [contenteditable="true"]').length > 0;
      return { htmlDir: htmlDir, bodyDir: bodyDir, styleInjected: styleInjected, hasContent: hasContent };
    } catch (e) {
      return { error: String(e) };
    }
  })();
`;

async function validateInjection(Runtime, url) {
  try {
    var r = await Runtime.evaluate({ expression: VALIDATION_SCRIPT, returnByValue: true });
    var v = r && r.result && r.result.value;
    if (!v) return;
    var ok = v.styleInjected && v.htmlDir === 'rtl' && v.hasContent;
    if (!ok && !domWarningEmitted) {
      domWarningEmitted = true;
      process.stderr.write('[WARN] Claude add-in DOM may have changed; selectors did not match. Check for an updated release of claude-word-rtl.\n');
      log('Validation failed for ' + url + ': ' + JSON.stringify(v));
      writeStatus('ERROR:dom-not-matched-after-inject');
    } else if (ok && inErrorState) {
      // Recovery: we were stuck in ERROR, but this tick validates clean.
      // Clear the flag and report CONNECTED so the tray goes green again.
      inErrorState = false;
      writeStatus('CONNECTED');
    }
  } catch (e) { /* ignore - next tick will retry */ }
}

async function attach(target) {
  if (attached.has(target.id)) return;
  try {
    var client = await CDP({ target: target.webSocketDebuggerUrl });
    var Page = client.Page, Runtime = client.Runtime;
    await Page.enable();
    await Runtime.enable();
    await Page.addScriptToEvaluateOnNewDocument({ source: INJECTOR_SCRIPT });
    var result = await Runtime.evaluate({ expression: INJECTOR_SCRIPT, returnByValue: true });
    log('Attached & injected: ' + target.url + ' -> ' + (result.result && result.result.value));
    writeStatus('CONNECTED');

    // Delayed validation: give the page 5s to settle (SPA hydration, async
    // chunks) before we declare the DOM "doesn't match".
    setTimeout(function () { validateInjection(Runtime, target.url); }, 5000);

    Page.on('frameNavigated', async function () {
      try {
        await Runtime.evaluate({ expression: INJECTOR_SCRIPT });
        // Re-run validation after navigation too, but the dedupe flag means
        // it only logs once per process.
        setTimeout(function () { validateInjection(Runtime, target.url); }, 5000);
      } catch (e) {}
    });

    client.on('disconnect', function () {
      log('Detached: ' + target.url);
      attached.delete(target.id);
      if (attached.size === 0) writeStatus('DISCONNECTED');
    });

    attached.set(target.id, client);
  } catch (err) {
    log('Attach failed for ' + target.url + ': ' + err.message);
    fileLog('attach error stack: ' + (err && err.stack ? err.stack : '(no stack)'));
  }
}

// Tick counter + last-logged signatures so we can log state transitions
// without spamming the file every 2s. We log: every listTargets error, the
// first successful tick, and any change in the set of matched targets.
var tickCount = 0;
var lastTargetsSig = null;
var lastListErrorMsg = null;
async function tick() {
  tickCount++;
  var targets;
  try {
    targets = await listTargets();
    if (lastListErrorMsg) {
      fileLog('listTargets recovered after error: ' + lastListErrorMsg);
      lastListErrorMsg = null;
    }
  } catch (e) {
    var msg = e && e.message ? e.message : String(e);
    if (msg !== lastListErrorMsg) {
      fileLog('listTargets failed (tick ' + tickCount + '): ' + msg);
      lastListErrorMsg = msg;
    }
    return;
  }
  var aliveIds = new Set(targets.map(function (t) { return t.id; }));
  for (var id of Array.from(attached.keys())) {
    if (!aliveIds.has(id)) attached.delete(id);
  }
  var pageTargets = targets.filter(function (t) { return t.type === 'page'; });
  var primaryMatches = pageTargets.filter(function (t) { return URL_PATTERN_PRIMARY.test(t.url || ''); });
  var matches = primaryMatches.length > 0
    ? primaryMatches
    : pageTargets.filter(function (t) { return URL_PATTERN_FALLBACK.test(t.url || ''); });
  var sig = 'total=' + targets.length + ' pages=' + pageTargets.length +
    ' matched=' + matches.length +
    ' urls=[' + pageTargets.map(function (t) { return t.url; }).join(' | ') + ']';
  if (sig !== lastTargetsSig) {
    fileLog('targets (tick ' + tickCount + '): ' + sig);
    lastTargetsSig = sig;
  }
  for (var i = 0; i < matches.length; i++) {
    var t = matches[i];
    if (attached.has(t.id)) continue;
    await attach(t);
  }
}

log('Claude RTL injector starting. Watching localhost:' + PORT);
log('Match pattern (primary):', URL_PATTERN_PRIMARY);
log('Match pattern (fallback):', URL_PATTERN_FALLBACK);
log('Ctrl+C to stop.');
setInterval(tick, POLL_MS);
tick();
